### PR TITLE
GHC 8.6.3

### PR DESCRIPTION
**Pull request by menelaos**

### CODE REVIEW

**Comment by mightybyte** [comment]
Excellent!  Thanks for the nice work.  Can you explain why you removed the `ListT` instance?  That will require a major version bump.

**Comment by menelaos** [comment]
I removed the instance because `ListT` has been marked as [deprecated](http://hackage.haskell.org/package/transformers-0.5.5.0/docs/Control-Monad-Trans-List.html) and I wanted to get rid of the warnings :-) Sorry, I should probably have opened a separate PR for that. Would you like me to add the instance back?

**Comment by menelaos** [comment]
Testing with GHC 8.6.4. The CI error seems to be a bug in GHC 8.2.1. Please let me know if you want any changes.

**Comment by Mikolaj** [comment]
It would be great if we could enable support for GHC 8.6. @mightybyte: may I help in any way?

**Comment by Mikolaj** [comment]
Actually, while we are at it, could we also support lens-4.17?

**Comment by Mikolaj** [comment]
And postgresql-simple-0.6.1, ideally?

**Comment by mightybyte** [comment]
I just merged this, but I'd really like to have all the tests passing.  I took a stab at fixing it with PR #53.  We'll see if the tests pass.

@Mikolaj After that PR finishes Travis, if it is still failing you could work on figuring out a fix.

**Comment by Mikolaj** [comment]
Success!

**Comment by mightybyte** [comment]
Ok, I just uploaded this to hackage as version 1.2.0.0.  Right now it's only a package candidate (https://hackage.haskell.org/package/snaplet-postgresql-simple-1.2.0.0/candidate).  Want to give it a try?  Once we've confirmed it is working I'll publish it as a full version release.

**Comment by Mikolaj** [comment]
It compiles and works. I don't know how much our client's code stresses the library, but 100% of tests passed in any case. Thank you!

**Comment by mightybyte** [comment]
Great, I'll go ahead and publish it.

**Comment by Mikolaj** [comment]
Splendid. Thank you very much.

**Pull request merged**
