### PR TITLE
withTransaction commits on mzero

### PR DESCRIPTION
**Pull request by sopvop**
withTransaction will commit even if monad is short-circuiting like Snap does.
Currently if you have code like
~~~~.haskell
doSomething key = withTransaction $ do
    v <- fromMaybe finishWith404 $ getFromDatabase key
    doMoreStuff v
~~~~
Transaction will not be commited or rolled back in case of pass. And since pooled connections can be reused by other handlers and will be executed in same transaction. In this case libpg reports warnings to stderr.

### CODE REVIEW

**Comment by lpsmith** [comment]
This is a fairly well know problem with the MonadCatchIO stuff.

However,   I'd be rather surprised that the connection would be reused,  as it _shouldn't_ be put back in the pool and _should_ be garbage collected.

**Comment by sopvop** [comment]
Well, I've got a bunch of "Transaction already running" messages from libpq, so I presumed connections were being reused.

**Comment by mightybyte** [comment]
@lpsmith I believe @sopvop is running on snap 1.0, so he shouldn't be using MonadCatchIO.

**Comment by lpsmith** [comment]
Ahh,  ok that makes sense;   withPG is using the correct bracket,  but `withTransactionMode` can't just use bracket because of the need to rollback on error.     So it's not surprising to me that `withTransactionMode` does need to be changed.

I still think I'm correct in the pre-1.0 case, though.    And I find it rather discomforting that this code needs to be changed at all.

In any case,  this would seem to confirm that monad-control's version of bracket works correctly on the Snap monad,  which is something I've been meaning to confirm for a while.  =)

**Pull request merged**
